version: '3'
services:
  mysql-db:
    container_name: mysql-db
    env_file:
      - .env
    image: "mysql/mysql-server:5.7" 
    ports:
      - "3306:3306"
    networks:
      nhan-sam-thuy-linh-network:
    environment:
      - MYSQL_ONETIME_PASSWORD=true
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}

    volumes:
        - ./mysql-data:/var/lib/mysql57:rw
        - ./mysql-init:/docker-entrypoint-initdb.d/:ro
        
#  web-nhan-sam-thuy-linh:
#    container_name: nhan-sam-thuy-linh
#    image: nhan-sam-thuy-linh:latest
#    build:
#      context: ./nhan-sam-thuy-linh
#      dockerfile: Dockerfile
#    working_dir: /nhan-sam-thuy-linh
#    restart: on-failure
#    volumes:
#      - ./nhan-sam-thuy-linh:/nhan-sam-thuy-linh
#    ports:
#      - "8088:8080"
#    depends_on:
#      - mysql-db
#    networks:
#      springboot-mysql-network:
#    environment:
#      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true
#    command: mvn clean spring-boot:run
    
networks:
    nhan-sam-thuy-linh-network: